### PR TITLE
Migrate context menu to NPM

### PR DESCRIPTION
**Pull request by denis-anisimov**
Part of flow#5489

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/65)

### CODE REVIEW

**Review by SomeoneToIgnore — APPROVED** [review]
`contextMenuConnector.js` needs to be adjusted, see the #5489 ticket description or my PR into `vaadin-iron-list` for some ideas.

> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/65#-:-LdO-sAh7WhhJCCLH3Rj:b-t323z8)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by SomeoneToIgnore — APPROVED** [review]
Also I'm not sure if you noticed, but I've moved this particular component under the `Kirill takes care of` section.

But I'm perfectly fine with you finishing the migration.
Here's my branch with more changes: `kb/update-to-flow-2`, I'm stuck at IT tests currently.

> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/65#-:-LdO0D1UC-BZ1t7G7NG8:bumld9z)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by SomeoneToIgnore** [comment]
> Also I'm not sure if you noticed, but I've moved this particular component under the Kirill takes care of section.

Ah, I see, the item got duplicated, sorry for that.

**Review by denis-anisimov — COMMENTED** [review]
Done.

> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/65#-:-LdOf6tz-SHbg3Up18an:b-896fix)* status: 5 of 10 files reviewed, all discussions resolved

**Review by SomeoneToIgnore — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/65#-:-LdOhoxkAwBUzP43d0Az:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by denis-anisimov — COMMENTED** [review]
> Dismissed @vaadin-bot from a discussion.
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/65)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
