### PR TITLE
Add APIs to the component

### PR DESCRIPTION
**Pull request by ZheSun88**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/6)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed, 1 unresolved discussion (waiting on @denis-anisimov)

---

*[a discussion](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/6#-LGVoBQ607XySysi7nxU:-LGVoBQ607XySysi7nxV:bjct60z) (no related file):*
Any test for the implemented functionality ?
Do we have demos ? Should it be demoed ?

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/6)*

**Review by ZheSun88 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/6)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @denis-anisimov)

*[a discussion](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/6#-LGVoBQ607XySysi7nxU:-LGYtJQVA2QZD8X2vcHm:b8whvxy) (no related file):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Any test for the implemented functionality ?
Do we have demos ? Should it be demoed ?
</blockquote></details>

Test case have added.  we have demos, but i dont think the added api is very valuable for demoing. So i have added them in to the testPage.  Some more demos will be added via doing the further implementation . 

---

**Review by pekam — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/6)* status: 1 of 3 files reviewed, 3 unresolved discussions (waiting on @denis-anisimov and @ZheSun88)

___
*[src/test/java/com/vaadin/flow/component/contextmenu/it/ContextMenuPage.java, line 37 at r3](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/6#-LGZvbGkBDFk9OvASvT3:-LGZvbGkBDFk9OvASvT4:b-milp2h) ([raw file](https://github.com/vaadin/vaadin-context-menu-flow/blob/637ffa2d6535ed388714b0d86fea1e1df304be2c/src/test/java/com/vaadin/flow/component/contextmenu/it/ContextMenuPage.java#L37)):*
> ```Java
>     }
> 
>     private void createMenuForAPITest() {
> ```

Rename to something more descriptive, eg. `addContextMenuWithOpenedChangeListener`
___
*[src/test/java/com/vaadin/flow/component/contextmenu/it/ContextMenuPageIT.java, line 42 at r3](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/6#-LGZw3L27cz1IarbwJXz:-LGZw3L27cz1IarbwJY-:b-3f2u8l) ([raw file](https://github.com/vaadin/vaadin-context-menu-flow/blob/637ffa2d6535ed388714b0d86fea1e1df304be2c/src/test/java/com/vaadin/flow/component/contextmenu/it/ContextMenuPageIT.java#L42)):*
> ```Java
> 
>     @Test
>     public void TestAPIs() {
> ```

Rename to something more descriptive, eg. `openedChangeListenerIsCalled_isOpenedReturnsCorrectValue`

**Review by ZheSun88 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/6)* status: 1 of 3 files reviewed, 3 unresolved discussions (waiting on @denis-anisimov and @pekam)

___
*[src/test/java/com/vaadin/flow/component/contextmenu/it/ContextMenuPage.java, line 37 at r3](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/6#-LGZvbGkBDFk9OvASvT3:-LGZzuP-3k5wnDE9jc8v:b-896fix) ([raw file](https://github.com/vaadin/vaadin-context-menu-flow/blob/637ffa2d6535ed388714b0d86fea1e1df304be2c/src/test/java/com/vaadin/flow/component/contextmenu/it/ContextMenuPage.java#L37)):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

Rename to something more descriptive, eg. `addContextMenuWithOpenedChangeListener`
</blockquote></details>

Done.
___
*[src/test/java/com/vaadin/flow/component/contextmenu/it/ContextMenuPageIT.java, line 42 at r3](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/6#-LGZw3L27cz1IarbwJXz:-LGZzuxTAD70-DFvklvs:b-896fix) ([raw file](https://github.com/vaadin/vaadin-context-menu-flow/blob/637ffa2d6535ed388714b0d86fea1e1df304be2c/src/test/java/com/vaadin/flow/component/contextmenu/it/ContextMenuPageIT.java#L42)):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

Rename to something more descriptive, eg. `openedChangeListenerIsCalled_isOpenedReturnsCorrectValue`
</blockquote></details>

Done.

**Review by denis-anisimov — COMMENTED** [review]
:lgtm: 

> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/6#-:-LG_JTu70Vqfc8Fr6wZB:bg7igkv)* status: all files reviewed, 1 unresolved discussion (waiting on @denis-anisimov)

**Review by denis-anisimov — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/6)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
