### PR TITLE
Extract ContextMenuBase class for extensibility (#14)

### PR DESCRIPTION
**Pull request by pleku**
Pick #14 from master branch to 1.0.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/17)

### CODE REVIEW

**Review by denis-anisimov — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/17)* status: all files reviewed, 3 unresolved discussions (waiting on @vaadin-bot and @denis-anisimov)

___
*[src/main/java/com/vaadin/flow/component/contextmenu/ContextMenu.java, line 36 at r1](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/17#-LJO4-vFBqJ6vEVrMPbV:-LJO4-vFBqJ6vEVrMPbW:b31icpe) ([raw file](https://github.com/vaadin/vaadin-context-menu-flow/blob/ab8c3e3485ef6ac947d51dd595eab4d7bfd3c2d9/src/main/java/com/vaadin/flow/component/contextmenu/ContextMenu.java#L36)):*
> ```
> super();
> ```

extra, but is minor.
___
*[src/main/java/com/vaadin/flow/component/contextmenu/MenuItem.java, line 39 at r1](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/17#-LJO4fxXE76Zg6vrlpjE:-LJO4fxXE76Zg6vrlpjF:b50wv0d) ([raw file](https://github.com/vaadin/vaadin-context-menu-flow/blob/ab8c3e3485ef6ac947d51dd595eab4d7bfd3c2d9/src/main/java/com/vaadin/flow/component/contextmenu/MenuItem.java#L39)):*
> ```
> MenuItem
> ```

package local CTOR?

If this class is intended to be used only internally then it makes sense to make class package local as well.
Otherwise CTOR should be also `public`.

**Review by pleku — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/17)* status: all files reviewed, 2 unresolved discussions (waiting on @vaadin-bot and @denis-anisimov)

___
*[src/main/java/com/vaadin/flow/component/contextmenu/ContextMenu.java, line 36 at r1](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/17#-LJO4-vFBqJ6vEVrMPbV:-LJOGzcv-n92yOW9pLvI:beosuex) ([raw file](https://github.com/vaadin/vaadin-context-menu-flow/blob/ab8c3e3485ef6ac947d51dd595eab4d7bfd3c2d9/src/main/java/com/vaadin/flow/component/contextmenu/ContextMenu.java#L36)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> ```
> super();
> ```

extra, but is minor.
</blockquote></details>

This is just a pick from `master`, so I don't want to deviate. The fixes should go to master and be then picked here I think
___
*[src/main/java/com/vaadin/flow/component/contextmenu/MenuItem.java, line 39 at r1](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/17#-LJO4fxXE76Zg6vrlpjE:-LJOH7B66sbZk9RX_cQ6:b-86x94l) ([raw file](https://github.com/vaadin/vaadin-context-menu-flow/blob/ab8c3e3485ef6ac947d51dd595eab4d7bfd3c2d9/src/main/java/com/vaadin/flow/component/contextmenu/MenuItem.java#L39)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> ```
> MenuItem
> ```

package local CTOR?

If this class is intended to be used only internally then it makes sense to make class package local as well.
Otherwise CTOR should be also `public`.
</blockquote></details>

Again, I have no idea about this. You've reviewed the original change so please ask yourself why did it pass then https://github.com/vaadin/vaadin-context-menu-flow/pull/14

**Review by denis-anisimov — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/17)* status: all files reviewed, 1 unresolved discussion (waiting on @vaadin-bot)

___
*[src/main/java/com/vaadin/flow/component/contextmenu/MenuItem.java, line 39 at r1](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/17#-LJO4fxXE76Zg6vrlpjE:-LJOYAIf2km4jeHfcrk5:byr4flj) ([raw file](https://github.com/vaadin/vaadin-context-menu-flow/blob/ab8c3e3485ef6ac947d51dd595eab4d7bfd3c2d9/src/main/java/com/vaadin/flow/component/contextmenu/MenuItem.java#L39)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Again, I have no idea about this. You've reviewed the original change so please ask yourself why did it pass then https://github.com/vaadin/vaadin-context-menu-flow/pull/14
</blockquote></details>

Right.

**Review by denis-anisimov — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/17#-:-LJOYD0C03EZ0BJvohts:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @vaadin-bot)

**Review by ZheSun88 — APPROVED** [review]
> Dismissed @vaadin-bot from a discussion.
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/17)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
