### PR TITLE
Introduce entry point method to process before-open event details

### PR DESCRIPTION
**Pull request by gatanaso**
This PR introduces the possibility for the context menu to process the event details sent from clients before it is being opened. It achieves that with the following updates:
- The client side target component can optionally introduce event details when it fires the `vaadin-context-menu-before-open`. This is achieved by checking if the `target` component defines it's own `getContextMenuBeforeOpenDetail` (which indicates that the `target` component wishes to provide additional event context) and introducing those details in the event data.
- The before open handler is updated such that a new method is introduced `onBeforeOpenMenu` that receives the event details. This method can process the details if needed and decide to open or not open the context menu (based on the returned value). By default it does nothing and just returns `true`, but sub-classes can easily override it and perform additional operations such as dynamically define new context menu items or decide to not open the context menu.

In part this is a first step towards solving #76 as it allows sub-classes the possibility to hook into the context menu "open" logic and perform some processing based on the event context details sent from the target component.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/99)

### CODE REVIEW

**Review by manolo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/99)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @gatanaso)

___
*[vaadin-context-menu-flow/src/main/java/com/vaadin/flow/component/contextmenu/ContextMenuBase.java, line 58 at r2](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/99#-LmsaiZ43PaCJRsg2S-O:-LmsaiZ539i-2GyDfO9C:b-pzsn16) ([raw file](https://github.com/vaadin/vaadin-context-menu-flow/blob/c8dff786f2d05b4137cc46dced5e8f2c71a8f820/vaadin-context-menu-flow/src/main/java/com/vaadin/flow/component/contextmenu/ContextMenuBase.java#L58)):*
> ```Java
>         extends GeneratedVaadinContextMenu<C> implements HasComponents {
> 
>     public static final String VAADIN_CONTEXT_MENU_BEFORE_OPEN_EVENT_DETAIL = "event.detail";
> ```

why not just `EVENT_DETAIL` it's worst read such a long name than a short name. `event.detail` is a JS convention, and does not have any relation to this concrete web component.

**Review by manolo — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/99)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @gatanaso)

___
*[vaadin-context-menu-flow/src/main/java/com/vaadin/flow/component/contextmenu/ContextMenuBase.java, line 344 at r2](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/99#-LmscXuP4kU6qmjCj-2U:-LmscXuP4kU6qmjCj-2V:b-rnlqiu) ([raw file](https://github.com/vaadin/vaadin-context-menu-flow/blob/c8dff786f2d05b4137cc46dced5e8f2c71a8f820/vaadin-context-menu-flow/src/main/java/com/vaadin/flow/component/contextmenu/ContextMenuBase.java#L344)):*
> ```Java
>     /**
>      * This method is an entry point that allows processing of the context menu
>      * before open event details.
> ```

Change the sentence to something more explanatory like:
`Decides whether to open the menu when the beforeOpenHandler is processed,   
  sub-classes can easily override it and perform additional operations in this phase.` 
___
*[vaadin-context-menu-flow/src/main/java/com/vaadin/flow/component/contextmenu/ContextMenuBase.java, line 360 at r2](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/99#-LmscCd674BUyrNHuZZh:-LmscCd674BUyrNHuZZi:b-sm97vh) ([raw file](https://github.com/vaadin/vaadin-context-menu-flow/blob/c8dff786f2d05b4137cc46dced5e8f2c71a8f820/vaadin-context-menu-flow/src/main/java/com/vaadin/flow/component/contextmenu/ContextMenuBase.java#L360)):*
> ```Java
>      *         otherwise.
>      */
>     protected boolean processBeforeOpenEventDetails(JsonObject eventDetail) {
> ```

The method name does not say to me so much about what it does. 
Perhaps `shouldOpenMenu()` `onBeforeOpenMenu()` ? or something more meaningful

**Review by manolo — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/99)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @gatanaso)

**Review by gatanaso — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/99)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @manolo)

___
*[vaadin-context-menu-flow/src/main/java/com/vaadin/flow/component/contextmenu/ContextMenuBase.java, line 58 at r2](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/99#-LmsaiZ43PaCJRsg2S-O:-LmseU_tBFFXxOJvwXHJ:bxr9rgf) ([raw file](https://github.com/vaadin/vaadin-context-menu-flow/blob/c8dff786f2d05b4137cc46dced5e8f2c71a8f820/vaadin-context-menu-flow/src/main/java/com/vaadin/flow/component/contextmenu/ContextMenuBase.java#L58)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

why not just `EVENT_DETAIL` it's worst read such a long name than a short name. `event.detail` is a JS convention, and does not have any relation to this concrete web component.
</blockquote></details>

Yeah, makes sense, will update it.
___
*[vaadin-context-menu-flow/src/main/java/com/vaadin/flow/component/contextmenu/ContextMenuBase.java, line 344 at r2](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/99#-LmscXuP4kU6qmjCj-2U:-Lmsen-g6m3IAWDR6nM1:buxxm7g) ([raw file](https://github.com/vaadin/vaadin-context-menu-flow/blob/c8dff786f2d05b4137cc46dced5e8f2c71a8f820/vaadin-context-menu-flow/src/main/java/com/vaadin/flow/component/contextmenu/ContextMenuBase.java#L344)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Change the sentence to something more explanatory like:
`Decides whether to open the menu when the beforeOpenHandler is processed,   
  sub-classes can easily override it and perform additional operations in this phase.` 
</blockquote></details>

Sounds good, will change it!
___
*[vaadin-context-menu-flow/src/main/java/com/vaadin/flow/component/contextmenu/ContextMenuBase.java, line 360 at r2](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/99#-LmscCd674BUyrNHuZZh:-LmsezLR4k4OtJmjtGMi:b-lic79d) ([raw file](https://github.com/vaadin/vaadin-context-menu-flow/blob/c8dff786f2d05b4137cc46dced5e8f2c71a8f820/vaadin-context-menu-flow/src/main/java/com/vaadin/flow/component/contextmenu/ContextMenuBase.java#L360)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

The method name does not say to me so much about what it does. 
Perhaps `shouldOpenMenu()` `onBeforeOpenMenu()` ? or something more meaningful 
</blockquote></details>

Yeah, I had a difficult time figuring out a good name here. I think `onBeforeOpenMenu` is a very good idea, will update it. Thank you!

**Review by manolo — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/99)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ZheSun88 — COMMENTED** [review]
just a reminder to the team. before merging this PR, you should consider to bump the master branch to `3.1-SNAPSHOT`, as this is a new feature.

> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/99#-:-LmwyEpLDOcGTnSVf1Ns:bpzv01l)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @manolo)

**Review by manolo — COMMENTED** [review]
Yes,  I think it is a good idea to increase the version.

> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/99#-:-Lmx6nD86S3HZwzAlt1J:b-rfmdv1)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @manolo)

**Review by manolo — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/99)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by gatanaso** [comment]
Created a separate PR for the snapshot version increase: https://github.com/vaadin/vaadin-context-menu-flow/pull/100

**Review by alvarezguille — CHANGES_REQUESTED** [review]
.

**Review by alvarezguille — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/99)* status: all files reviewed, 1 unresolved discussion (waiting on @gatanaso)

*[a discussion](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/99#-LnD9n8aA4UJDIhlCekX:-LnD9n8aA4UJDIhlCekY:b-e2ha7g) (no related file):*
Tests are missing, I'll block for now

---

**Review by DiegoCardoso — APPROVED** [review]
> Reviewed 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/99)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
