### PR TITLE
Add setOpenOnClick method

### PR DESCRIPTION
**Pull request by ZheSun88**
This API enables the left click on opening context menu.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/8)

### CODE REVIEW

**Review by pekam — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/8)* status: all files reviewed, 4 unresolved discussions (waiting on @ZheSun88)

___
*[src/main/java/com/vaadin/flow/component/contextmenu/ContextMenu.java, line 124 at r1](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/8#-LGjUEJlBk4CqxoJggqQ:-LGjUEJlBk4CqxoJggqR:b-ghrx1m) ([raw file](https://github.com/vaadin/vaadin-context-menu-flow/blob/410d4e86d0beb2fc177895bf186ef9ab8020004a/src/main/java/com/vaadin/flow/component/contextmenu/ContextMenu.java#L124)):*
> ```Java
>      * <p>
>      * By default, this will return {@code false} and context menu can be opened
>      * with a right click or a long touch on mobile device.
> ```

devices.
___
*[src/main/java/com/vaadin/flow/component/contextmenu/ContextMenu.java, line 126 at r1](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/8#-LGjUJO061DRuLuDtMuS:-LGjUJO061DRuLuDtMuT:b2zirxy) ([raw file](https://github.com/vaadin/vaadin-context-menu-flow/blob/410d4e86d0beb2fc177895bf186ef9ab8020004a/src/main/java/com/vaadin/flow/component/contextmenu/ContextMenu.java#L126)):*
> ```Java
>      * with a right click or a long touch on mobile device.
>      * 
>      * @return if {@code true}, the context menu can be opened with left click
> ```

ordering:
`@return {@code true} if the context menu`
___
*[src/main/java/com/vaadin/flow/component/contextmenu/ContextMenu.java, line 130 at r1](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/8#-LGjSGVr4-3qNp-1foTJ:-LGjSGVr4-3qNp-1foTK:b-1ouhdo) ([raw file](https://github.com/vaadin/vaadin-context-menu-flow/blob/410d4e86d0beb2fc177895bf186ef9ab8020004a/src/main/java/com/vaadin/flow/component/contextmenu/ContextMenu.java#L130)):*
> ```Java
>      */
>     public boolean isOpenOnClick() {
>         return (getOpenOnString() == "click") ? true : false;
> ```

The ` ? true : false;` doesn't add anything to this, since the previous part already returns the boolean.

Also, use `equals` instead of `==`
___
*[src/test/java/com/vaadin/flow/component/contextmenu/it/ContextMenuPage.java, line 84 at r1](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/8#-LGjSpHL1SvGMTBW0gzY:-LGjSpHL1SvGMTBW0gzZ:b-uv7i6k) ([raw file](https://github.com/vaadin/vaadin-context-menu-flow/blob/410d4e86d0beb2fc177895bf186ef9ab8020004a/src/test/java/com/vaadin/flow/component/contextmenu/it/ContextMenuPage.java#L84)):*
> ```Java
>             message.setText("Current state is " + contextMenu.isOpenOnClick());
>         });
>         
> ```

remove whitespace

**Review by ZheSun88 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/8)* status: 1 of 3 files reviewed, 4 unresolved discussions (waiting on @pekam and @ZheSun88)

___
*[src/main/java/com/vaadin/flow/component/contextmenu/ContextMenu.java, line 124 at r1](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/8#-LGjUEJlBk4CqxoJggqQ:-LGjWCnJ2i9WS2wI6bwM:b-a78qyr) ([raw file](https://github.com/vaadin/vaadin-context-menu-flow/blob/410d4e86d0beb2fc177895bf186ef9ab8020004a/src/main/java/com/vaadin/flow/component/contextmenu/ContextMenu.java#L124)):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

devices.
</blockquote></details>

not done.. LOL
___
*[src/main/java/com/vaadin/flow/component/contextmenu/ContextMenu.java, line 126 at r1](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/8#-LGjUJO061DRuLuDtMuS:-LGjWG0OCoSXTY19SA3p:bb7f2mf) ([raw file](https://github.com/vaadin/vaadin-context-menu-flow/blob/410d4e86d0beb2fc177895bf186ef9ab8020004a/src/main/java/com/vaadin/flow/component/contextmenu/ContextMenu.java#L126)):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

ordering:
`@return {@code true} if the context menu`
</blockquote></details>

done
___
*[src/main/java/com/vaadin/flow/component/contextmenu/ContextMenu.java, line 130 at r1](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/8#-LGjSGVr4-3qNp-1foTJ:-LGjWGfh6OIumgYIt1Va:b-896fix) ([raw file](https://github.com/vaadin/vaadin-context-menu-flow/blob/410d4e86d0beb2fc177895bf186ef9ab8020004a/src/main/java/com/vaadin/flow/component/contextmenu/ContextMenu.java#L130)):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

The ` ? true : false;` doesn't add anything to this, since the previous part already returns the boolean.

Also, use `equals` instead of `==`
</blockquote></details>

Done.
___
*[src/test/java/com/vaadin/flow/component/contextmenu/it/ContextMenuPage.java, line 84 at r1](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/8#-LGjSpHL1SvGMTBW0gzY:-LGjWH6v7062Ya0wjgGz:b-896fix) ([raw file](https://github.com/vaadin/vaadin-context-menu-flow/blob/410d4e86d0beb2fc177895bf186ef9ab8020004a/src/test/java/com/vaadin/flow/component/contextmenu/it/ContextMenuPage.java#L84)):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

remove whitespace
</blockquote></details>

Done.

**Review by pekam — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/8)* status: 1 of 3 files reviewed, 5 unresolved discussions (waiting on @pekam and @ZheSun88)

___
*[src/test/java/com/vaadin/flow/component/contextmenu/it/ContextMenuPageIT.java, line 59 at r1](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/8#-LGjW4P-062c50PYQirk:-LGjW4P-062c50PYQirl:bbbo2zu) ([raw file](https://github.com/vaadin/vaadin-context-menu-flow/blob/410d4e86d0beb2fc177895bf186ef9ab8020004a/src/test/java/com/vaadin/flow/component/contextmenu/it/ContextMenuPageIT.java#L59)):*
> ```Java
> 
>     @Test
>     public void setOpenOnClickIsCalled_IsOpenOnClickReturnsCorrentValue() {
> ```

this tests also that the functionality is correct and not only that getter returns correct value. So naming could be better.

**Review by pekam — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/8)* status: all files reviewed, 1 unresolved discussion (waiting on @ZheSun88)

**Review by pekam — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/8)* status: all files reviewed, 1 unresolved discussion (waiting on @ZheSun88)

___
*[src/test/java/com/vaadin/flow/component/contextmenu/it/ContextMenuPageIT.java, line 59 at r1](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/8#-LGjW4P-062c50PYQirk:-LGjWrUQ4FV-iiLlgfmz:b-lq1e3f) ([raw file](https://github.com/vaadin/vaadin-context-menu-flow/blob/410d4e86d0beb2fc177895bf186ef9ab8020004a/src/test/java/com/vaadin/flow/component/contextmenu/it/ContextMenuPageIT.java#L59)):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

this tests also that the functionality is correct and not only that getter returns correct value. So naming could be better. 
</blockquote></details>

`setOpenOnClick_opensCorrectlyWithEitherLeftOrRightClick_getterReturnsCorrect`

**Review by pekam — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/8)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by pekam — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/8)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ZheSun88 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/8)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[src/test/java/com/vaadin/flow/component/contextmenu/it/ContextMenuPageIT.java, line 59 at r1](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/8#-LGjW4P-062c50PYQirk:-LGjYpZz72MbWngzAdCN:b-gpcaix) ([raw file](https://github.com/vaadin/vaadin-context-menu-flow/blob/410d4e86d0beb2fc177895bf186ef9ab8020004a/src/test/java/com/vaadin/flow/component/contextmenu/it/ContextMenuPageIT.java#L59)):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

`setOpenOnClick_opensCorrectlyWithEitherLeftOrRightClick_getterReturnsCorrect`
</blockquote></details>

Done. please Pekka. :P

**Review by pekam — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/8)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by pekam — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/8)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
