### PR TITLE
Initial setup and implementation

### PR DESCRIPTION
**Pull request by pekam**
This adds the project setup and a ContextMenu implementation
with a basic support for adding/removing components and
setting the target component. A lot of the implementation is
copied from Dialog.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/3)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Reviewed 8 of 10 files at r1, 1 of 1 files at r2.
Review status: 9 of 10 files reviewed, 2 unresolved discussions (waiting on @denis-anisimov and @pekam)

---

*[src/main/java/com/vaadin/flow/component/contextmenu/ContextMenu.java, line 97 at r2](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/3#-LFQpKzhDV3Rz2us63mB:-LFQpKzhDV3Rz2us63mC:b-jjww8r) ([raw file](https://github.com/vaadin/vaadin-context-menu-flow/blob/837ebe8cfd9a2d361afe801fb1792e4b2bd3d224/src/main/java/com/vaadin/flow/component/contextmenu/ContextMenu.java#L97)):*
> ```
>  assert components != null;
> ```

Neither of those `assert`s (here, in the cycle and in the `remove`  methods) may be `assert`.

`assert` should be used when we are self-checking our own code.
It's absolutely possible that user provide a `null`   either as an argument or has a `null` in the array.
So we should throw an exception instead.
Usually `Objects.requireNonNull` should be used (or custom `IllegalArgumentException`).

---

*[src/test/java/com/vaadin/flow/component/contextmenu/it/ContextMenuDemoIT.java, line 67 at r2](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/3#-LFQqS4iC4V0MXazZiuY:-LFQqS4iC4V0MXazZiuZ:bco8sni) ([raw file](https://github.com/vaadin/vaadin-context-menu-flow/blob/837ebe8cfd9a2d361afe801fb1792e4b2bd3d224/src/test/java/com/vaadin/flow/component/contextmenu/it/ContextMenuDemoIT.java#L67)):*
> ```
> getTestPath()
> ```

Use  `@TestPath`?

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/3)*

**Comment by pekam** [comment]
Review status: 8 of 10 files reviewed, 2 unresolved discussions (waiting on @denis-anisimov and @pekam)

---

*[src/main/java/com/vaadin/flow/component/contextmenu/ContextMenu.java, line 97 at r2](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/3#-LFQpKzhDV3Rz2us63mB:-LFQsyIoAKsESZoqnWP8:b-896fix) ([raw file](https://github.com/vaadin/vaadin-context-menu-flow/blob/837ebe8cfd9a2d361afe801fb1792e4b2bd3d224/src/main/java/com/vaadin/flow/component/contextmenu/ContextMenu.java#L97)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> ```
>  assert components != null;
> ```

Neither of those `assert`s (here, in the cycle and in the `remove`  methods) may be `assert`.

`assert` should be used when we are self-checking our own code.
It's absolutely possible that user provide a `null`   either as an argument or has a `null` in the array.
So we should throw an exception instead.
Usually `Objects.requireNonNull` should be used (or custom `IllegalArgumentException`).
</blockquote></details>

Done.

---

*[src/test/java/com/vaadin/flow/component/contextmenu/it/ContextMenuDemoIT.java, line 67 at r2](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/3#-LFQqS4iC4V0MXazZiuY:-LFQu7Cl6yf9-TIFsRx8:b-s8ecjl) ([raw file](https://github.com/vaadin/vaadin-context-menu-flow/blob/837ebe8cfd9a2d361afe801fb1792e4b2bd3d224/src/test/java/com/vaadin/flow/component/contextmenu/it/ContextMenuDemoIT.java#L67)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> ```
> getTestPath()
> ```

Use  `@TestPath`?
</blockquote></details>

It doesn't seem to work for the demo ITs.

The problem is in `flow-component-demo-helpers`: We have `ComponentDemoTest` there which we extend for the demo ITs, and it doesn't have the `@TestPath` parsing. Other ITs extend `AbstractComponentIT` which has this feature.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/3)*

**Comment by denis-anisimov** [comment]
Reviewed 1 of 10 files at r1.
Review status: 9 of 10 files reviewed, 3 unresolved discussions (waiting on @denis-anisimov)

---

*[src/test/java/com/vaadin/flow/component/contextmenu/ContextMenuTest.java, line 34 at r2](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/3#-LFQusjM-jYW2MLkfHXo:-LFQusjM-jYW2MLkfHXp:b-fcqa6c) ([raw file](https://github.com/vaadin/vaadin-context-menu-flow/blob/837ebe8cfd9a2d361afe801fb1792e4b2bd3d224/src/test/java/com/vaadin/flow/component/contextmenu/ContextMenuTest.java#L34)):*
> ```
> createContextMenuWithComponents_componentsArePartOfGetChildren
> ```

This method should check that `target`  is not a child.

And separately : `removeAll` doesn't remove the `target`.

`removeAll` is a different method and requires separate tests.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/3)*

**Comment by pekam** [comment]
Review status: 8 of 10 files reviewed, 3 unresolved discussions (waiting on @denis-anisimov)

---

*[src/test/java/com/vaadin/flow/component/contextmenu/ContextMenuTest.java, line 34 at r2](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/3#-LFQusjM-jYW2MLkfHXo:-LFR-Ium1-BiINsUn8-p:b-ypklec) ([raw file](https://github.com/vaadin/vaadin-context-menu-flow/blob/837ebe8cfd9a2d361afe801fb1792e4b2bd3d224/src/test/java/com/vaadin/flow/component/contextmenu/ContextMenuTest.java#L34)):*
> This method should check that target  is not a child.

Is this related to the assumption that the target component needs to be the child of the context menu? I don't know if you saw my message in slack and the implementation here but that was a false assumption.

There's no component-level API for adding components directly to the `<vaadin-context-menu>`.

The target can be added to the overlay by calling both `setTarget(target)` and `add(target)`, which is kinda stupid, but in that case `getChildren()` should return the target also.

I added a test case for `removeAll()`

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/3)*

**Comment by denis-anisimov** [comment]
Reviewed 1 of 1 files at r3, 1 of 1 files at r4.
Review status: all files reviewed, 4 unresolved discussions (waiting on @denis-anisimov)

---

*[src/main/java/com/vaadin/flow/component/contextmenu/ContextMenu.java, line 101 at r3](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/3#-LFQvsLx7SvdvuqfoBGH:-LFQvsLx7SvdvuqfoBGI:bi1zj67) ([raw file](https://github.com/vaadin/vaadin-context-menu-flow/blob/8ee5e6b67bdaa3d02872bd9dcf66831b78e980c6/src/main/java/com/vaadin/flow/component/contextmenu/ContextMenu.java#L101)):*
> ```
> Component
> ```

What's the `Component` is clear only from the code.
But as an external user I don't know what you are referring here (the same is true for the `Components` above but there it's at least a name of the argument though it's not the exact name and compiled class may miss the argument name).

It needs a clarification in terms of the argument value. 

---

*[src/test/java/com/vaadin/flow/component/contextmenu/ContextMenuTest.java, line 34 at r2](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/3#-LFQusjM-jYW2MLkfHXo:-LFR17Fr7kMTWkI1Zmz8:b8rtie8) ([raw file](https://github.com/vaadin/vaadin-context-menu-flow/blob/837ebe8cfd9a2d361afe801fb1792e4b2bd3d224/src/test/java/com/vaadin/flow/component/contextmenu/ContextMenuTest.java#L34)):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

> This method should check that target  is not a child.

Is this related to the assumption that the target component needs to be the child of the context menu? I don't know if you saw my message in slack and the implementation here but that was a false assumption.

There's no component-level API for adding components directly to the `<vaadin-context-menu>`.

The target can be added to the overlay by calling both `setTarget(target)` and `add(target)`, which is kinda stupid, but in that case `getChildren()` should return the target also.

I added a test case for `removeAll()`
</blockquote></details>

`setTarget()` doesn't add the component as a child, right ?
So `getChildren()

---

*[src/test/java/com/vaadin/flow/component/contextmenu/ContextMenuTest.java, line 69 at r4](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/3#-LFR1MR72Mu8E3spXo7I:-LFR1MR72Mu8E3spXo7J:b95aen0) ([raw file](https://github.com/vaadin/vaadin-context-menu-flow/blob/211364e11555decc145f695ecdf261aaf79531b8/src/test/java/com/vaadin/flow/component/contextmenu/ContextMenuTest.java#L69)):*
> ```
> addComponents_removeAll_getChildrenReturnsEmpt
> ```

The same issue with `setTarget()`.
The target should not be removed.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/3)*

**Comment by pekam** [comment]
Review status: all files reviewed, 4 unresolved discussions (waiting on @denis-anisimov)

---

*[src/main/java/com/vaadin/flow/component/contextmenu/ContextMenu.java, line 101 at r3](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/3#-LFQvsLx7SvdvuqfoBGH:-LFR25-f537fUeiW_Kvb:bww5sin) ([raw file](https://github.com/vaadin/vaadin-context-menu-flow/blob/8ee5e6b67bdaa3d02872bd9dcf66831b78e980c6/src/main/java/com/vaadin/flow/component/contextmenu/ContextMenu.java#L101)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> ```
> Component
> ```

What's the `Component` is clear only from the code.
But as an external user I don't know what you are referring here (the same is true for the `Components` above but there it's at least a name of the argument though it's not the exact name and compiled class may miss the argument name).

It needs a clarification in terms of the argument value. 
</blockquote></details>

IMO it's really unambiguous what it means when you see the message and the method where it happened:
```
NPE: Component to add cannot be null
in ContextMenu.add
```

I'm not sure I know what you'd like me to do. Is something like `Cannot provide null values as arguments` good?

---

*[src/test/java/com/vaadin/flow/component/contextmenu/ContextMenuTest.java, line 34 at r2](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/3#-LFQusjM-jYW2MLkfHXo:-LFR3aRxDzu2Rrvu9FpX:blvlcl6) ([raw file](https://github.com/vaadin/vaadin-context-menu-flow/blob/837ebe8cfd9a2d361afe801fb1792e4b2bd3d224/src/test/java/com/vaadin/flow/component/contextmenu/ContextMenuTest.java#L34)):*
> setTarget() doesn't add the component as a child, right ?

True.

So it seems completely random to test that target is not handled as a child component when there is no code that would do anything like that. The target is set as the property `listenOn`.

It's almost the same as testing that setting a `value` property for a component doesn't add a child to the component.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/3)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed, 3 unresolved discussions (waiting on @denis-anisimov)

---

*[src/main/java/com/vaadin/flow/component/contextmenu/ContextMenu.java, line 101 at r3](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/3#-LFQvsLx7SvdvuqfoBGH:-LFR5Wci5BHzOHpLthIh:b-8rkjd7) ([raw file](https://github.com/vaadin/vaadin-context-menu-flow/blob/8ee5e6b67bdaa3d02872bd9dcf66831b78e980c6/src/main/java/com/vaadin/flow/component/contextmenu/ContextMenu.java#L101)):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

IMO it's really unambiguous what it means when you see the message and the method where it happened:
```
NPE: Component to add cannot be null
in ContextMenu.add
```

I'm not sure I know what you'd like me to do. Is something like `Cannot provide null values as arguments` good?
</blockquote></details>

Ah well. This is vararg. Not an array. I forgot about that.
Then it's OK with vararg.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/3)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed, 3 unresolved discussions (waiting on @denis-anisimov)

---

*[src/test/java/com/vaadin/flow/component/contextmenu/ContextMenuTest.java, line 34 at r2](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/3#-LFQusjM-jYW2MLkfHXo:-LFR5s2M2hTE6ZdldKGj:b-o9f71y) ([raw file](https://github.com/vaadin/vaadin-context-menu-flow/blob/837ebe8cfd9a2d361afe801fb1792e4b2bd3d224/src/test/java/com/vaadin/flow/component/contextmenu/ContextMenuTest.java#L34)):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

> setTarget() doesn't add the component as a child, right ?

True.

So it seems completely random to test that target is not handled as a child component when there is no code that would do anything like that. The target is set as the property `listenOn`.

It's almost the same as testing that setting a `value` property for a component doesn't add a child to the component.
</blockquote></details>

Yes and no.
`ComextMenu`  follows the composite pattern. So it has children. Every component which is extra for a component pattern looks suspicious. There is always a chance that it may become a child (may be accidentally in the future). 
This is a regression test which forecast and prevents this mistake.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/3)*

**Comment by pekam** [comment]
Review status: 9 of 10 files reviewed, 3 unresolved discussions (waiting on @denis-anisimov)

---

*[src/test/java/com/vaadin/flow/component/contextmenu/ContextMenuTest.java, line 34 at r2](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/3#-LFQusjM-jYW2MLkfHXo:-LFR9onWCM8pm2AFsGGg:b-6dv1be) ([raw file](https://github.com/vaadin/vaadin-context-menu-flow/blob/837ebe8cfd9a2d361afe801fb1792e4b2bd3d224/src/test/java/com/vaadin/flow/component/contextmenu/ContextMenuTest.java#L34)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Yes and no.
`ComextMenu`  follows the composite pattern. So it has children. Every component which is extra for a component pattern looks suspicious. There is always a chance that it may become a child (may be accidentally in the future). 
This is a regression test which forecast and prevents this mistake.
</blockquote></details>

Ok then, done.

(The test I previously added for `removeAll()` was actually duplicate of the first test so I removed that part)

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/3)*

**Comment by denis-anisimov** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r5.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/3#-:-LFRCI8O5yZx7FDUmGAq:bnfp4nl)*

**Pull request merged**
