### PR TITLE
Use list-box inside and add addItem() methods

### PR DESCRIPTION
**Pull request by pekam**
To make the common use-case (based on the web component demos) easy,
the contents of the overlay are wrapped inside a vaadin-list-box and
vaadin-item elements can be added with text or component content + click
handlers easily with addItem().

Also added convenience constructor and missing close() method.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/7)

### CODE REVIEW

**Review by denis-anisimov — CHANGES_REQUESTED** [review]
> Reviewed 5 of 6 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/7)* status: all files reviewed, 1 unresolved discussion (waiting on @denis-anisimov and @pekam)

___
*[src/main/java/com/vaadin/flow/component/contextmenu/ContextMenu.java, line 151 at r2](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/7#-LGcqOqo9ckFTU3hYsCa:-LGcqOqo9ckFTU3hYsCb:blch4z4) ([raw file](https://github.com/vaadin/vaadin-context-menu-flow/blob/dce4e646b316494fb5f5c9a01b3081166c1c5ceb/src/main/java/com/vaadin/flow/component/contextmenu/ContextMenu.java#L151)):*
> ```
> addItem(
> ```

The difference between `addItem` and `add` is not really clear for me.
Both of them add the components. From the impl I see that in the first case the component is wrapped. 
How can I know what's the benefit of this method? Is it a submenu ?

The javadoc should be improved to clarify the difference between two methods.
Also may be some renaming should be done: I'm not able to understand what implementation does even if I see it (locally here in this method without navigating through all over the code).

**Review by pekam — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/7)* status: all files reviewed, 1 unresolved discussion (waiting on @denis-anisimov)

___
*[src/main/java/com/vaadin/flow/component/contextmenu/ContextMenu.java, line 151 at r2](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/7#-LGcqOqo9ckFTU3hYsCa:-LGd7qqbCvQmietT3YVA:b-6psbqk) ([raw file](https://github.com/vaadin/vaadin-context-menu-flow/blob/dce4e646b316494fb5f5c9a01b3081166c1c5ceb/src/main/java/com/vaadin/flow/component/contextmenu/ContextMenu.java#L151)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> ```
> addItem(
> ```

The difference between `addItem` and `add` is not really clear for me.
Both of them add the components. From the impl I see that in the first case the component is wrapped. 
How can I know what's the benefit of this method? Is it a submenu ?

The javadoc should be improved to clarify the difference between two methods.
Also may be some renaming should be done: I'm not able to understand what implementation does even if I see it (locally here in this method without navigating through all over the code).
</blockquote></details>

The suggested way to use the web component is to have a `vaadin-list-box` inside it. And inside list-box there are `vaadin-item` components. These have the highlight feature when you hover over them. This is the common use case and that's why there are `addItem()` helpers for it, so you can just pass a string or component and the click handler.

But the simple `add()` method from `HasComponents` provides the option to use the context menu simply as an overlay which opens on right-click and you can provide the contents how ever you like, without wrapping everything inside high-lighted items. This is why I think it's good to have `add()` also.

I think that the demo gives a lot better view of this. But I also understand now your concerns about the API...

Is it enough if I improve the javadocs something like this:
```
Adds a new item component with the given child components to the context menu overlay.

This is a convenience method for the use case where you have a list of high-lightable
MenuItems inside the overlay. If you want to configure the contents of the overlay
without wrapping them inside MenuItems, or if you just want to add some non-high-lightable
components between the items, use the add() method.
```

And for the `add` method:
```
Adds the given components into the context menu overlay.

For the common use case of having a list of high-lightable items inside the overlay,
you can use the convenience method addItem(Component...). 

The elements in the DOM will not be children of the
{@code <vaadin-context-menu>} element, but will be inserted into an
overlay that is attached into the {@code <body>}.
```

**Review by pekam — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/7)* status: all files reviewed, 1 unresolved discussion (waiting on @denis-anisimov)

___
*[src/main/java/com/vaadin/flow/component/contextmenu/ContextMenu.java, line 151 at r2](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/7#-LGcqOqo9ckFTU3hYsCa:-LGdEstOEW04-B88D6dc:b-q66hbg) ([raw file](https://github.com/vaadin/vaadin-context-menu-flow/blob/dce4e646b316494fb5f5c9a01b3081166c1c5ceb/src/main/java/com/vaadin/flow/component/contextmenu/ContextMenu.java#L151)):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

The suggested way to use the web component is to have a `vaadin-list-box` inside it. And inside list-box there are `vaadin-item` components. These have the highlight feature when you hover over them. This is the common use case and that's why there are `addItem()` helpers for it, so you can just pass a string or component and the click handler.

But the simple `add()` method from `HasComponents` provides the option to use the context menu simply as an overlay which opens on right-click and you can provide the contents how ever you like, without wrapping everything inside high-lighted items. This is why I think it's good to have `add()` also.

I think that the demo gives a lot better view of this. But I also understand now your concerns about the API...

Is it enough if I improve the javadocs something like this:
```
Adds a new item component with the given child components to the context menu overlay.

This is a convenience method for the use case where you have a list of high-lightable
MenuItems inside the overlay. If you want to configure the contents of the overlay
without wrapping them inside MenuItems, or if you just want to add some non-high-lightable
components between the items, use the add() method.
```

And for the `add` method:
```
Adds the given components into the context menu overlay.

For the common use case of having a list of high-lightable items inside the overlay,
you can use the convenience method addItem(Component...). 

The elements in the DOM will not be children of the
{@code <vaadin-context-menu>} element, but will be inserted into an
overlay that is attached into the {@code <body>}.
```

</blockquote></details>

Another thing that I just realized: I should maybe just remove this method and `addItem(String text)`. So we would have only the overloads which have the click listeners. Because it doesn't really make sense to add high-lightable items which don't do anything when you click them. And you could still achieve the same by using `add()` but it's not really something we should encourage by having the helper API.

**Review by denis-anisimov — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/7)* status: all files reviewed, 1 unresolved discussion (waiting on @denis-anisimov)

___
*[src/main/java/com/vaadin/flow/component/contextmenu/ContextMenu.java, line 151 at r2](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/7#-LGcqOqo9ckFTU3hYsCa:-LGdFtyD1OkOc_5E1MKQ:b-4sl7od) ([raw file](https://github.com/vaadin/vaadin-context-menu-flow/blob/dce4e646b316494fb5f5c9a01b3081166c1c5ceb/src/main/java/com/vaadin/flow/component/contextmenu/ContextMenu.java#L151)):*
<details><summary><i>Previously, pekam (Pekka Maanpää) wrote…</i></summary><blockquote>

Another thing that I just realized: I should maybe just remove this method and `addItem(String text)`. So we would have only the overloads which have the click listeners. Because it doesn't really make sense to add high-lightable items which don't do anything when you click them. And you could still achieve the same by using `add()` but it's not really something we should encourage by having the helper API.
</blockquote></details>

The new version of javadoc is better.

Also please add `@see ` with crossreferences to the similar methods.

Up to you about `add(String)`. If there will be a need we may add it later on.

**Review by pekam — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/7)* status: 1 of 6 files reviewed, 1 unresolved discussion (waiting on @denis-anisimov)

___
*[src/main/java/com/vaadin/flow/component/contextmenu/ContextMenu.java, line 151 at r2](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/7#-LGcqOqo9ckFTU3hYsCa:-LGdYK9rE0l0NTopGPvd:b-jwtnp1) ([raw file](https://github.com/vaadin/vaadin-context-menu-flow/blob/dce4e646b316494fb5f5c9a01b3081166c1c5ceb/src/main/java/com/vaadin/flow/component/contextmenu/ContextMenu.java#L151)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

The new version of javadoc is better.

Also please add `@see ` with crossreferences to the similar methods.

Up to you about `add(String)`. If there will be a need we may add it later on.
</blockquote></details>

Done.
Removed the overloads that don't add click listener and improved javadocs.

**Review by ZheSun88 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/7)* status: 1 of 6 files reviewed, 2 unresolved discussions (waiting on @denis-anisimov and @pekam)

___
*[pom.xml, line 39 at r3](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/7#-LGd_odg9tOpdK_mmToi:-LGd_odg9tOpdK_mmToj:by5i2ku) ([raw file](https://github.com/vaadin/vaadin-context-menu-flow/blob/6cb87fdbd852c096a1ba646c5f00db00d25c5609/pom.xml#L39)):*
> ```XML
>             <groupId>org.webjars.bowergithub.vaadin</groupId>
>             <artifactId>vaadin-list-box</artifactId>
>             <version>[1.0.0,1.0.999]</version>
> ```

This range is incorrect, because the current `context-menu` webcompennt has the support the for `material` theme, but this `list-box` doesn't.  list-box starts to support `material` theme from 1.1.0-alpha1

**Review by denis-anisimov — APPROVED** [review]
> Reviewed 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/7)* status: all files reviewed, 1 unresolved discussion (waiting on @pekam)

**Review by pekam — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/7)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @denis-anisimov and @ZheSun88)

___
*[pom.xml, line 39 at r3](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/7#-LGd_odg9tOpdK_mmToi:-LGdbkWu1OxhTjjKm0gE:b-896fix) ([raw file](https://github.com/vaadin/vaadin-context-menu-flow/blob/6cb87fdbd852c096a1ba646c5f00db00d25c5609/pom.xml#L39)):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

This range is incorrect, because the current `context-menu` webcompennt has the support the for `material` theme, but this `list-box` doesn't.  list-box starts to support `material` theme from 1.1.0-alpha1
</blockquote></details>

Done.

**Review by ZheSun88 — APPROVED** [review]

**Review by ZheSun88 — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/7)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
