### PR TITLE
Update readme with the new link to docs and branching

### PR DESCRIPTION
**Pull request by denis-anisimov**
Part of fix for vaadin-button-flow/issues/83

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/21)

### CODE REVIEW

**Review by ZheSun88 — CHANGES_REQUESTED** [review]
sign the CLA

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/21#-:-LN95d1fDzYg8vYySmbA:b-siqknp)* status: all files reviewed, 1 unresolved discussion (waiting on @denis-anisimov)

___
*[README.md, line 7 at r1](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/21#-LN95vhgCfEf4Qh1DHtk:-LN95vhgCfEf4Qh1DHtl:b3v6hqw) ([raw file](https://github.com/vaadin/vaadin-context-menu-flow/blob/984eccd85fc5aa8fbbdccf768e7ab8512bcf26bd/README.md#L7)):*
> ```
> - `1.0` branch is Vaadin 10 LTS (Flow/Flow-component version 1.0)
> ```

1.0 branch should be Vaadin 10 compatible, but this component should not be LTS
same as grid 1.1 branch

**Review by denis-anisimov — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/21)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ZheSun88)

___
*[README.md, line 7 at r1](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/21#-LN95vhgCfEf4Qh1DHtk:-LN9CJ7hAhn9ZTsTM-vX:b-896fix) ([raw file](https://github.com/vaadin/vaadin-context-menu-flow/blob/984eccd85fc5aa8fbbdccf768e7ab8512bcf26bd/README.md#L7)):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

> ```
> - `1.0` branch is Vaadin 10 LTS (Flow/Flow-component version 1.0)
> ```

1.0 branch should be Vaadin 10 compatible, but this component should not be LTS
same as grid 1.1 branch 
</blockquote></details>

Done.

**Review by ZheSun88 — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/21)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[README.md, line 7 at r1](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/21#-LN95vhgCfEf4Qh1DHtk:-LN9IZkj3qIdwiJvdjDV:by2qqfd) ([raw file](https://github.com/vaadin/vaadin-context-menu-flow/blob/984eccd85fc5aa8fbbdccf768e7ab8512bcf26bd/README.md#L7)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

mentioning `(Flow version 1.0, but no LTS support)`

**Review by ZheSun88 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/21)* status: all files reviewed, 1 unresolved discussion (waiting on @denis-anisimov)

**Review by ZheSun88 — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/21)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
