### PR TITLE
Restructure project into several modules

### PR DESCRIPTION
**Pull request by denis-anisimov**
Part of https://github.com/vaadin/flow-component-base/issues/117

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/40)

### CODE REVIEW

**Review by ujoni — CHANGES_REQUESTED** [review]
> Reviewed 23 of 30 files at r1, 7 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/40)* status: all files reviewed, 2 unresolved discussions (waiting on @denis-anisimov)

___
*[vaadin-context-menu-flow/pom.xml, line 22 at r2](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/40#-LXYWkqT30vk15BokhbP:-LXYWkqT30vk15BokhbQ:b-lutweu) ([raw file](https://github.com/vaadin/vaadin-context-menu-flow/blob/3f7c6f71334504cf4dfaba05a016b2c2e9bc9b50/vaadin-context-menu-flow/pom.xml#L22)):*
> ```XML
>             <groupId>org.webjars.bowergithub.vaadin</groupId>
>             <artifactId>vaadin-context-menu</artifactId>
>             <version>4.3.0-alpha1</version>
> ```

This should be `4.3.0-beta1`.
___
*[vaadin-context-menu-flow-testbench/src/main/java/ContextMenuElement.java, line 1 at r2](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/40#-LXYXt-12UFQ6jmuIMDi:-LXYXt-12UFQ6jmuIMDj:b8g8kzr) ([raw file](https://github.com/vaadin/vaadin-context-menu-flow/blob/3f7c6f71334504cf4dfaba05a016b2c2e9bc9b50/vaadin-context-menu-flow-testbench/src/main/java/ContextMenuElement.java#L1)):*
> ```Java
> import com.vaadin.testbench.TestBenchElement;
> ```

Shouldn't it read `package com.vaadin.flow.component.contextmenu.testbench;` here?

**Review by denis-anisimov — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/40)* status: all files reviewed, 2 unresolved discussions (waiting on @ujoni)

___
*[vaadin-context-menu-flow/pom.xml, line 22 at r2](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/40#-LXYWkqT30vk15BokhbP:-LXYaE3i5uKBpdBc6zPq:bsj5y0w) ([raw file](https://github.com/vaadin/vaadin-context-menu-flow/blob/3f7c6f71334504cf4dfaba05a016b2c2e9bc9b50/vaadin-context-menu-flow/pom.xml#L22)):*
<details><summary><i>Previously, ujoni (Joni) wrote…</i></summary><blockquote>

This should be `4.3.0-beta1`.
</blockquote></details>

Not sure that it should be `4.3.0-beta1` in _this_ PR.
But since we merge all commits one by one I can change it.
___
*[vaadin-context-menu-flow-testbench/src/main/java/ContextMenuElement.java, line 1 at r2](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/40#-LXYXt-12UFQ6jmuIMDi:-LXYbME72_2MPK7XzywI:b-4ik6u4) ([raw file](https://github.com/vaadin/vaadin-context-menu-flow/blob/3f7c6f71334504cf4dfaba05a016b2c2e9bc9b50/vaadin-context-menu-flow-testbench/src/main/java/ContextMenuElement.java#L1)):*
<details><summary><i>Previously, ujoni (Joni) wrote…</i></summary><blockquote>

Shouldn't it read `package com.vaadin.flow.component.contextmenu.testbench;` here?
</blockquote></details>

Right, thanks for catching.

**Review by ujoni — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/40)* status: 28 of 30 files reviewed, 1 unresolved discussion (waiting on @denis-anisimov and @ujoni)

___
*[vaadin-context-menu-flow-testbench/src/main/java/ContextMenuElement.java, line 1 at r2](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/40#-LXYXt-12UFQ6jmuIMDi:-LXYdMFn3l6bmj60baW-:bjy2sc0) ([raw file](https://github.com/vaadin/vaadin-context-menu-flow/blob/3f7c6f71334504cf4dfaba05a016b2c2e9bc9b50/vaadin-context-menu-flow-testbench/src/main/java/ContextMenuElement.java#L1)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Right, thanks for catching.
</blockquote></details>

Should it be in a `testbench` package? I only now noticed that this is under grid, but in any case; other Elements are in a `testbench` package.

Or should it be `grid.testbench.contextmenu`?

**Review by denis-anisimov — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/40)* status: 28 of 30 files reviewed, 1 unresolved discussion (waiting on @ujoni)

___
*[vaadin-context-menu-flow-testbench/src/main/java/ContextMenuElement.java, line 1 at r2](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/40#-LXYXt-12UFQ6jmuIMDi:-LXYgqiq0lLC-ZBoKrMN:b-lgtkm3) ([raw file](https://github.com/vaadin/vaadin-context-menu-flow/blob/3f7c6f71334504cf4dfaba05a016b2c2e9bc9b50/vaadin-context-menu-flow-testbench/src/main/java/ContextMenuElement.java#L1)):*
<details><summary><i>Previously, ujoni (Joni) wrote…</i></summary><blockquote>

Should it be in a `testbench` package? I only now noticed that this is under grid, but in any case; other Elements are in a `testbench` package.

Or should it be `grid.testbench.contextmenu`?
</blockquote></details>

Apparently I'm sick even more than I thought is I do such stupid mistakes.

**Review by denis-anisimov — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/40)* status: 28 of 30 files reviewed, 1 unresolved discussion (waiting on @ujoni)

___
*[vaadin-context-menu-flow-testbench/src/main/java/ContextMenuElement.java, line 1 at r2](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/40#-LXYXt-12UFQ6jmuIMDi:-LXYir2TBhwKb89psc0k:b-896fix) ([raw file](https://github.com/vaadin/vaadin-context-menu-flow/blob/3f7c6f71334504cf4dfaba05a016b2c2e9bc9b50/vaadin-context-menu-flow-testbench/src/main/java/ContextMenuElement.java#L1)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Apparently I'm sick even more than I thought is I do such stupid mistakes.
</blockquote></details>

Done.

**Review by ujoni — APPROVED** [review]
> Reviewed 1 of 2 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-context-menu-flow/40)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
